version: '3.4'

volumes:
  system.db:
    name: ${DB_CONTAINER:-system.db}

services:
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Identity/Dockerfile
    depends_on: 
      - system.db
  wedding.api:
    image: ${DOCKER_REGISTRY-}weddingapi
    build:
      context: .
      dockerfile: Wedding/Dockerfile
    depends_on: 
      - system.db
  
  system.db:
    container_name: System.Db
    image: mcr.microsoft.com/mssql/server:2022-latest